name: Release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yaml'

env:
  VERSION: "1.0"
  USER: Mikk155
  REPOSITORY: ripent.py

jobs:
  Windows:
    needs: release
    name: Win32
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile ripent.py

      - name: Release
        uses: xresloader/upload-to-github-release@v1.6.0
        with:
          file: "dist/ripent.exe;ripent.py;rules.json"
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}
          target_owner: ${{ env.USER }}
          target_repo: ${{ env.REPOSITORY }}
          update_latest_release: true
          default_release_name: "Rip Ent"
          update_release_body_path: "changelog.md"
          draft: false
          prerelease: false

  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile ripent.py

      - name: Release
        uses: xresloader/upload-to-github-release@v1.6.0
        with:
          file: "dist/ripent"
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}
          target_owner: ${{ env.USER }}
          target_repo: ${{ env.REPOSITORY }}
          update_latest_release: true
